# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Musicly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Musicly

  pod 'RealmSwift'

  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'MusiclyTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'MusiclyUITests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end


